# @package _group_
type: informer
d_model: 512
n_head: 8
e_layers: 2
d_layers: 1
s_layers: 3,2,1
d_ff: 512
factor: 5
dropout: 0.05
k_size: 32
num_layers: 1
pred_len: 200
attn: prob
dropout_p: 0.1
mix: yes

