random_seed: ~
use_cuda: yes
mode: train
history_length: 120
forward_length: 80
train:
    epochs: 800
    max_epochs_stop: 100
    batch_size: 128
    eval_epochs: 10
    num_workers: 8

test:
    plt_cnt: 20
    test_dir: ~

defaults:
    - model: vaecl
    - train/optim: adam
    - train/schedule: exp
    - dataset: west

hydra:
    run:
        dir: ckpt/${now:%Y-%m-%d_%H-%M-%S}
